[tool.black]
line-length = 100

[tool.isort]
multi_line_output = 3
line_length = 100
use_parentheses = true
lines_after_imports = 2
force_sort_within_sections = true
include_trailing_comma = true
known_third_party = ["pytest"]

[pylint]
max-line-length=100
